# Generated by Django 4.0.3 on 2022-03-06 06:02

from django.db import migrations, models
import location.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', location.fields.LowerCharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='place')),
            ],
        ),
    ]
