# Generated by Django 4.0.3 on 2022-03-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('large', 'Large'), ('small', 'Small')], default='small', max_length=10),
        ),
    ]
